apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: flask-app-image:latest  # Replace with your Flask image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000  # Flask app runs on port 5000 inside the container
          envFrom:
            - configMapRef:
                name: flask-config
            - secretRef:
                name: flask-secret
