apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  FLASK_SECRET_KEY: c2VjcmV0a2V5c3RhY2t5bWZsYWFrZ2ZsYW5rc3Bkcw==  # Base64 encoded string (for example "secretkeystack")
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=  # Base64 encoded MongoDB username (e.g., "admin")
  MONGO_PASSWORD: c3Ryb25ncGFzc3dvcmQxMjM=  # Base64 encoded MongoDB password (e.g., "strongpassword123")
